# Generated by Django 2.0.6 on 2019-02-25 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('checking', models.DecimalField(decimal_places=4, max_digits=16)),
                ('savings', models.DecimalField(decimal_places=4, max_digits=16)),
                ('dateTimeOpen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
